### ISSUE TITLE
Does not compile on Ubuntu 19.10

### ISSUE THREAD

**Issue by Russ-Holmes** [projectM-visualizer/projectm#274]
Compile fails with:

`/usr/bin/ld: ../projectM-qt/libprojectM_qt.a(qprojectmwidget_moc.o):(.data.rel.ro+0x0): undefined reference to `QGLWidget::staticMetaObject'
collect2: error: ld returned 1 exit status
`
On both RC4 and RC6
Installed QT version 5.12.4+dfsg-4ubuntu1

Any suggestions?

**Comment by revmischa** [comment]
#273 - can you test this fix please?

**Comment by revmischa** [comment]
This should be fixed on master now, please let us know if you have any further issues., Thanks!

**Comment by mamantoha** [comment]
Hi @revmischa . Unfortunately, it's not fixed on master. Please reopen this issue.

**Comment by revmischa** [comment]
Same issue as #280 #283

**Comment by mamantoha** [comment]
I was able to make it work on Ubuntu 19.10

```
./configure --enable-qt --enable-gles LIBS="-lQt5Gui -lQt5OpenGL"
make
sudo make install
```

<img width="812" alt="Screenshot_20191218_135644" src="https://user-images.githubusercontent.com/61285/71084754-a41af180-219e-11ea-88c7-8fc228b30179.png">

Hope this helps someone.

**Comment by Button4Button** [comment]
That's impressive... is that the latest RC or stable release?  I've been
trying on Linux Mint 19.3 (beta) and failing consistently.

**Comment by mamantoha** [comment]
@Button4Button from the master branch

**Comment by Russ-Holmes** [comment]
Yes, I was able to compile 3.1.1-rc7 on ubuntu 19.10 with:

`sudo apt install libtool pkg-config libglm-dev qt5-default qtdeclarative5-dev libgles2-mesa-dev
./configure --enable-qt --enable-gles LIBS="-lQt5Gui -lQt5OpenGL"
make
sudo make install`

**Comment by revmischa** [comment]
I am on ubuntu 19.04 and I can simply run
```
./configure --enable-qt
make
```
And it builds without errors. On master (3.1.1-rc7)

**Comment by revmischa** [comment]
I just upgraded to ubuntu 19.10 and got:
```
depbase=`echo ConfigFile.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I../..  -Wall -Wchar-subscripts -Wformat-security -Wpointer-arith -Wshadow -Wsign-compare -Wtype-limits -DDATADIR_PATH=\""/usr/local/share/projectM"\" -I../../vendor  -include ../../config.h -DSYSCONFDIR=\""/usr/local/etc"\" -DPROJECTM_PREFIX=\""/usr/local"\" -DRESOURCE_PREFIX=\""share/projectM"\" -I../../src/libprojectM -I../../src/libprojectM/Renderer -I../../src/projectM-qt  -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_QMLTEST_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_DBUS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_TESTLIB_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR="/tmp" -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuickTest -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtTest -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++  -fPIC   -g -O2 -pthread -std=c++11 -MT ConfigFile.o -MD -MP -MF $depbase.Tpo -c -o ConfigFile.o ConfigFile.cpp &&\
mv -f $depbase.Tpo $depbase.Po
/bin/bash ../../libtool  --tag=CXX   --mode=link g++  -g -O2 -pthread -std=c++11 -static -fPIC /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so /usr/lib/x86_64-linux-gnu/libQt5QuickTest.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5X11Extras.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Concurrent.so /usr/lib/x86_64-linux-gnu/libQt5DBus.so /usr/lib/x86_64-linux-gnu/libQt5Qml.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Test.so /usr/lib/x86_64-linux-gnu/libQt5Sql.so /usr/lib/x86_64-linux-gnu/libQt5Xml.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread    -o projectM-jack qprojectM-jack.o ConfigFile.o ../projectM-qt/libprojectM_qt.a -ljack -lpthread /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so /usr/lib/x86_64-linux-gnu/libQt5QuickTest.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5X11Extras.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Concurrent.so /usr/lib/x86_64-linux-gnu/libQt5DBus.so /usr/lib/x86_64-linux-gnu/libQt5Qml.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Test.so /usr/lib/x86_64-linux-gnu/libQt5Sql.so /usr/lib/x86_64-linux-gnu/libQt5Xml.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   ../libprojectM/libprojectM.la -lGL  -ldl  -pthread
libtool: link: g++ -g -O2 -pthread -std=c++11 -fPIC /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so /usr/lib/x86_64-linux-gnu/libQt5QuickTest.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5X11Extras.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Concurrent.so /usr/lib/x86_64-linux-gnu/libQt5DBus.so /usr/lib/x86_64-linux-gnu/libQt5Qml.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Test.so /usr/lib/x86_64-linux-gnu/libQt5Sql.so /usr/lib/x86_64-linux-gnu/libQt5Xml.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -o projectM-jack qprojectM-jack.o ConfigFile.o /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so /usr/lib/x86_64-linux-gnu/libQt5QuickTest.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5X11Extras.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Concurrent.so /usr/lib/x86_64-linux-gnu/libQt5DBus.so /usr/lib/x86_64-linux-gnu/libQt5Qml.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Test.so /usr/lib/x86_64-linux-gnu/libQt5Sql.so /usr/lib/x86_64-linux-gnu/libQt5Xml.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -pthread  ../projectM-qt/libprojectM_qt.a -ljack -lpthread ../libprojectM/.libs/libprojectM.a -lGL -ldl -pthread
/usr/bin/ld: ../projectM-qt/libprojectM_qt.a(qprojectm_mainwindow.o): undefined reference to symbol '_ZN5QIconC1Ev@@Qt_5'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libQt5Gui.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:494: projectM-jack] Error 1
```
Interesting.
Any ideas for a fix?

**Comment by Russ-Holmes** [comment]
revmischa, have you tried running configure with these options? Fixed it for me.

`./configure --enable-qt --enable-gles LIBS="-lQt5Gui -lQt5OpenGL"`

**Comment by revmischa** [comment]
@Russ-Holmes that does appear to make it compile on 19.10! Now, how can we fix this permanently?

**Comment by revmischa** [comment]
Added those options in https://github.com/projectM-visualizer/projectm/pull/293

**Comment by mamantoha** [comment]
I think we can close this as resolved.
