### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by gsus24** [projectM-visualizer/projectm#444]
Hello
can not build on Ubuntu 18.04 

make && make install-strip

thorwn error:

FileScanner.cpp:145:18: error: use of undeclared identifier 'fts_open'

Seem an Java error, maybe NDK, too.
OpenJDK 11.0.7 and NDK-r22 is installed.

Can somebody told me with which versions it should run?

Thanks

**Comment by revmischa** [comment]
Did you try running `./configure` first? It should set `HAVE_FTS_H` correctly
Do you see an error about not finding`fts.h`?

**Comment by revmischa** [comment]
https://github.com/projectM-visualizer/projectm/blob/fd1d235a059714a3cdf1504d7ffe4ef4c286fe02/src/libprojectM/FileScanner.cpp#L14 relevant code

**Comment by gsus24** [comment]
./configure is for linux build, right?

I run ./configure-ndk and checking for fts.h was ok, no error.

**Comment by revmischa** [comment]
Not sure about android, but I would think autoconf would work there too
Can try undefining `HAVE_FTS_H` and it should build

**Comment by gsus24** [comment]
Thanks,  ./configure-ndk and make, run without errors.
I edit 
[https://github.com/projectM-visualizer/projectm/blob/fd1d235a059714a3cdf1504d7ffe4ef4c286fe02/src/libprojectM/FileScanner.cpp#L130](url)
from `ifdef` to `ifndef`

But still unable to import and build the projectm-android folder in Android Studio.
Get error:
> A problem occurred configuring project ':app'.
> java.lang.NullPointerException (no error message)

**Comment by gsus24** [comment]
Can´t get it import. So started to create a new project and get it installed, but failed with 
`java.lang.UnsatisfiedLinkError: dlopen failed: library "F:/StudioProjects/projectmscratch/app/src/main/cpp/../../../jniLibs/.......... not found`

I had this error in another project and solved it with lower ndk version.
Tried 22 and 19 with the same error

Somebody out there who get it work? Whats versions of ndk, gradle,...

**Comment by gsus24** [comment]
@revmischa thanks again, get it import and run on device.

In build.gradle under android added packagingOption
`android {
        ...
        packagingOptions {
            pickFirst 'lib/armeabi-v7a/libprojectM.so'
        }
       ...
    }`
It was my mistake. Compiled the libraries for arm64-8va first and this results dlopen to failed.
With standard armeabi-v7a it do what it should ;)

To compile the libs for other architecture, i am going to open a new thread.
