### ISSUE TITLE
build errors and missing presets for android sample project

### ISSUE THREAD

**Issue by dkanada** [projectM-visualizer/projectm#500]
On a fresh clone I get the following errors when trying to build for Android.

```
FileScanner.cpp:150:18: error: use of undeclared identifier 'fts_open'
FileScanner.cpp:164:20: error: use of undeclared identifier 'fts_read'
FileScanner.cpp:184:5: error: use of undeclared identifier 'fts_close'; did you mean 'fclose'?
FileScanner.cpp:184:15: error: cannot initialize a parameter of type 'FILE *' (aka '__sFILE *') with an lvalue of type 'FTS *'
```

I used these commands in different configurations to actually build the library.

```
./autogen.sh
./configure-ndk

make
make install-strip
```

As mentioned in #444 I tried running `./configure` before `./configure-ndk` which had no effect on the errors. I also tried inverting the `HAVE_FTS_H` compile flags in `FileScanner.cpp` since that was also referenced, which technically fixes the build. However, the sample app refuses to pick up any presets, and I have a hunch the FileScanner changes are to blame. The `fts.h` file seems to be found when `./configure` and `./configure-ndk` are run so I'm not sure why it doesn't actually build. Another related issue might be #396 since it has at least one similar error message.

```
./configure-ndk
[...]
checking for fts.h... yes
[...]
```

I was able to confirm the presets exist within the cache directory. In fact, it seems like the new preset directory structure has issues on Android, which doesn't properly handle the subfolders and needed changes to work properly. I also tried filtering out all files without the `.milk` prefix during asset extraction, which had no effect.

**Comment by dkanada** [comment]
@kblaschke any news on the new build toolchain for Android devices? Just checking in to see if a new build attempt would be worth a try with cmake or the old system.

**Comment by kblaschke** [comment]
The library (libprojectM.so) builds fine using the new CMake build system and a recent NDK.

Then there's the actual Android app, which has the Java Native Interface wrapper for libprojectM and the actual Java app code. The Gradle scripts seem to have some issues finding a recent NDK (complaining about a missing `platforms` dir), so there might be some additional work required on the Android app project to make it compile with a recent Android SDK/Studio. @PeterMalkin  created the project, so he might know more about Android development and can possibly help out here.

**Comment by dkanada** [comment]
I noticed the `platforms` issue already and it worked a while ago when using a slightly older version of the NDK as noted above, so it sounds like I can give it another try at this point. Thanks for the update!

**Comment by dkanada** [comment]
So the build worked with CMake after some effort, which feels like progress. I had to apply the two changes you listed in [this comment](https://github.com/projectM-visualizer/projectm/issues/500#issuecomment-858739529) even after making sure I was on the latest commit from master. I also had to remove the `add_subdirectory(projectM-sdl)` line from `CMakeLists.txt` in the source directory since it seemed to be getting called regardless.

After those modifications I was able to get `libprojectM.so` for the Android project, but now the build over there is failing. This new error wasn't happening before, and it looks like some kind of issue finding the `include` files since this is the only reference to `PCM.hpp` in the JNI wrapper. I tried the CMake build with 3.6.4111459 and 3.18.1 to no avail, and also updated the target SDK version within the Android project.

```
projectm/src/projectm-android/app/src/main/cpp/jni.cpp:93
error: undefined reference to 'PCM::addPCM16Data(short const*, short)'
```

**Comment by dkanada** [comment]
So the build worked with CMake after some effort, which feels like progress. I had to apply the two changes you listed in [this comment](projectM-visualizer/examples-android#1) even after pulling the latest commit from master. I also had to remove the line below from `CMakeLists.txt` in the source directory since it seemed to be getting called regardless of the SDL build flag.

```
add_subdirectory(projectM-sdl)
```

At the moment, I have a functional build and the demo project is running perfectly. The only issue I'm left with is a missing OpenMP library at runtime in the Android project I'm *actually* trying to modify. The closest topic I could find online was this [issue](https://github.com/android/ndk/issues/1028) regarding build flags for OpenMP inclusion and this [error report](https://github.com/Tencent/ncnn/issues/976) on another repository.

```
java.lang.UnsatisfiedLinkError: dlopen failed: library "libomp.so" not found
    at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
    at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
    at java.lang.System.loadLibrary(System.java:1667)
    [...]
    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1541)
    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
```

**Comment by sachinsshah33** [comment]
Hi, I have really been struggling for many days to generate multiple `.so` files for different **Android Architectures**, such as:
**armeabi-v7a
arm64-v8a
...**

I am not so skilled in **CMake & NDK**, but nevertheless I have tried so many things, however none seem to be getting me what I need.

The only thing I have managed to to get me an `.so` file is the **Quickstart** section in **BUILDING-cmake.md**:
```mkdir build
cd build
cmake ..
make -j8```
But I did not specify an **Architecture** type so I don't think the `.so` file produced by this is the one I need, unless this `.so` file is generic and I can include it in all subfolders in **jniLibs** for the Android project:
e.g. `/Users/username/Downloads/projectm-master/src/projectm-android/app/jniLibs/armeabi-v7a`
But I don't think this is correct because of the difference between **armeabi-v7a** and **x86_64**, I’m not quite sure.

I have tried to run this command in terminal in the **root** of this projectM folder **/Users/username/Downloads/projectm-master**:
```cmake -GNinja \
    -DCMAKE_VERBOSE_MAKEFILE=1 \
    -DENABLE_SDL=OFF \
    -DENABLE_GLES=ON \
    -DANDROID_ABI=arm64-v8a \
    -DANDROID_PLATFORM=android-30 \
    -DANDROID_NDK=/Users/username/Library/Android/sdk/ndk/23.1.7779620/ \
    -DCMAKE_TOOLCHAIN_FILE=/Users/username/Library/Android/sdk/ndk/23.1.7779620/build/cmake/android.toolchain.cmake```

I have tried running the above on both Linux and macOS, but they both give me this error:
```CMake Error at CMakeLists.txt:119 (message):
  OpenGL ES 3 support is currently only available for Linux platforms.```
So I deleted that check in the same root **CMakeLists.txt** file. I hope my deletion is correct because I know I am generating the `.so` file for Android and not for Linux...

So I re-run the `cmake -GNinja...` command again and this gives me next error on both Linux and macOS:
``Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY
  OPENGL_INCLUDE_DIR)```
Even though I confirm I have OpenGL installed on both Linux and macOS, using something like: 
`glxinfo | grep "OpenGL version"`


So I tried the older way referenced in this commit:
https://github.com/projectM-visualizer/projectm/commit/87e16c14aa454c8990acab53e9b46d1603c0457b
```$ ./autogen.sh
$ ./configure
$ ./configure-ndk
$ sudo make -j`nproc` $ sudo make install-strip```
But this gave me some error which is noted in the commit:
https://github.com/projectM-visualizer/projectm/commit/87e16c14aa454c8990acab53e9b46d1603c0457b 
`WIP: crashes in trying to link egl`
 I also see this **IMPORTANT NOTE** in: 
 https://github.com/projectM-visualizer/projectm/blob/master/BUILDING.md
`Currently, CMake build support is still in active development and considered unfinished…`
So this confuses me and makes me wonder how you guys got it working haha 

Anyway, I then tried the latest source files that contained **autogen.sh** but this gave me the errors at the top of this thread
```FileScanner.cpp:150:18: error: use of undeclared identifier 'fts_open'
FileScanner.cpp:164:20: error: use of undeclared identifier 'fts_read'
FileScanner.cpp:184:5: error: use of undeclared identifier 'fts_close'```

And so I've just been going round in circles trying to get one of these ways to work but none of them seem to give the `.so` files that I require.

Please can you let me know what I'm doing incorrectly or if I am missing anything? 
My understanding is that I need to first Build the projectM library into different `.so` files each for a different Android Architecture. To do this I need to run `cmake` against the `CMakeLists.txt` in the **root directory**..
And then once I have the different `.so` files I can put them into their respective folders in the Android app, and then work on the **Android JNI** side of it, which I have to then run `cmake` against the `CMakeLists.txt` in the following directory:
`/Users/username/Downloads/projectm-master/src/projectm-android/app/src/main/cpp`
  If this is not the correct approach then I’d appreciate it if you can point me in the right direction please.
  
 Thanks, and sorry for the wall of text, if you'd like any more info/logs I'd be happy to provide them :)
