### ISSUE TITLE
libprojectm: Qt PulseAudio CMake wrong linker path

### ISSUE THREAD

**Issue by digitalcircuit** [projectM-visualizer/projectm#543]
## In short
**Describe the bug**
* `projectM-pulseaudio` build variant fails to build with CMake on Ubuntu 20.04 & 21.04
  * Specific build variant: `cmake .. -DENABLE_SDL=OFF -DENABLE_SDL_UI=OFF -DENABLE_PULSEAUDIO=ON`

*See also: [pull request #536: libprojectm: Fix static DL_LIBS for Qt PulseAudio](https://github.com/projectM-visualizer/projectm/pull/536 )*

**Screenshots**
```
[100%] Linking CXX executable projectM-pulseaudio
/usr/bin/ld: ../libprojectM/libprojectM.a(NativePresetFactory.cpp.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libdl.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [src/projectM-pulseaudio/CMakeFiles/projectM-pulseaudio.dir/build.make:168: src/projectM-pulseaudio/projectM-pulseaudio] Error 1
make[1]: *** [CMakeFiles/Makefile2:673: src/projectM-pulseaudio/CMakeFiles/projectM-pulseaudio.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

![Screenshot of two VirtualBox virtual machines showing the results of following the compilation steps.  Both end in the same error message as mentioned earlier in this pull request, except Ubuntu 21.04 references '10' instead of '9' due to updates.](https://zorro.casa/sync/Hosting/Utilities/Development/projectM/pr/fix-build-static-pulseaudio/Screenshot%20-%20projectM%20CMake%20build%20test%20Ubuntu%2020.04%20and%2021.04.png#v1 )

**Desktop (please complete the following information):**
 - Application: Qt with PulseAudio
 - OS: Linux (Kubuntu 20.04, Ubuntu 20.04, Ubuntu 21.04)
 - Version: [commit hash 8446784](https://github.com/projectM-visualizer/projectm/commit/844678472e434986a6c94de02d3e3aa3deab60a6 )

**Additional context**

### Steps
1.  Install Ubuntu (20.04.3 LTS and 21.04) with "install third-party drivers" checked
2.  Install updates, reboot
3.  Install dependencies from https://github.com/projectM-visualizer/projectm/blob/master/BUILDING.md#install-the-build-tools-and-dependencies
```
sudo apt install build-essential libgl1-mesa-dev mesa-common-dev libsdl2-dev libglm-dev
sudo apt install qtbase5-dev # For building Qt-based UIs
```
4.  Fetch sources
```
sudo apt install git # Probably already installed
git clone https://github.com/projectM-visualizer/projectm.git /path/to/local/repo
cd /path/to/local/repo
git fetch --all --tags
```
5.  Configure with CMake [with verbose build according to instructions](https://github.com/projectM-visualizer/projectm/pull/536#issuecomment-927619576 )
```
sudo apt install cmake
mkdir build
cd build
cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DENABLE_SDL=OFF -DENABLE_SDL_UI=OFF -DENABLE_PULSEAUDIO=ON -DCMAKE_INSTALL_PREFIX=/usr/local ..
```
6.  Try to compile
```
make

# For ease of following output, disabled concurrent building
#make -j$(nproc)
```
7.  Confirm file exists

*Ubuntu 20.04.3 LTS*
```
ls -l /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libdl.so
```

*Ubuntu 21.04*
```
ls -l /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libdl.so
```

### Expected
projectM compiles successfully.

### Results
Same compilation error.

[Download link for full compilation log for Ubuntu 20.04.3 LTS](https://zorro.casa/sync/Hosting/Utilities/Development/projectM/issues/libprojectm-qt-pulse-cmake-wrong-path/build-log-2021-9-27-20.04-verbose.log.txt )

[Download link for full compilation log for Ubuntu 21.04](https://zorro.casa/sync/Hosting/Utilities/Development/projectM/issues/libprojectm-qt-pulse-cmake-wrong-path/build-log-2021-9-27-21.04-verbose.log.txt )

**Comment by kblaschke** [comment]
Root cause is that libNAtivePresetFactory is still being built, even if native presets are disabled. Also, this library is not linked to libdl.so but uses dlopen(), which actually causes the build failure on some distros.

There's a PR open to mitigate the dynamic linker issue, I'll provide another PR to fully disable libNativePresetFactory from being built if disabled, which is the default case (native presets are quite problematic in many ways and might be removed completely in a future release).

**Comment by kblaschke** [comment]
A PR fixing the build issues was merged yesterday, if native presets are disabled (which is the default), no libdl.so is required anymore. If they are enabled, libdl.so is now linked to all executables as a transitive dependency.
